field: 4bb33121-5de9-43b1-add8-ad915602704c
fieldLayouts:
  4dfc74ae-0642-402b-9b58-fec9780bb0ad:
    tabs:
      -
        elements:
          -
            fieldUid: 91d67e1c-acd2-41d9-9f33-b40812fc297b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  91d67e1c-acd2-41d9-9f33-b40812fc297b:
    contentColumnType: text
    fieldGroup: null
    handle: code
    instructions: ''
    name: Code
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: code
name: Code
sortOrder: 4
