field: 4bb33121-5de9-43b1-add8-ad915602704c
fieldLayouts:
  f6ed1221-ffb3-42f8-b0d3-ef7888f9454b:
    tabs:
      -
        elements:
          -
            fieldUid: 67d7c94b-096f-4545-9b59-18b556c51565
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 348d0274-04f2-435d-bcd3-db712d182c0e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  348d0274-04f2-435d-bcd3-db712d182c0e:
    contentColumnType: text
    fieldGroup: null
    handle: cite
    instructions: ''
    name: Cite
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  67d7c94b-096f-4545-9b59-18b556c51565:
    contentColumnType: text
    fieldGroup: null
    handle: quote
    instructions: ''
    name: Quote
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: quote
name: Quote
sortOrder: 3
