contentColumnType: string
fieldGroup: b101b2e5-3692-494a-9a88-a9054f0e26be
handle: navigation
instructions: ''
name: Navigation
searchable: false
settings:
  contentTable: '{{%matrixcontent_navigation}}'
  maxBlocks: '6'
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
