fieldLayouts:
  2d682b6d-cf94-44b7-980f-ec25df38bba5:
    tabs:
      -
        elements:
          -
            fieldUid: 6e426b5b-d7ff-4617-9749-f54ecd209e70
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 0e557d11-fea8-4380-9bd4-56312139d927
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 246fa870-fd49-4236-9550-d4cdf6dd4ec6
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c74ed7dd-1632-4d16-a71e-42bc5e35d6eb
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Address
        sortOrder: 2
      -
        elements:
          -
            fieldUid: d9d86d07-b2a4-4b49-8021-c8ef13af1404
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Navigation
        sortOrder: 3
handle: footer
name: Footer
