fieldLayouts:
  925a7de7-a0db-46fc-8131-323c444da7a3:
    tabs:
      -
        elements:
          -
            fieldUid: 246fa870-fd49-4236-9550-d4cdf6dd4ec6
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c74ed7dd-1632-4d16-a71e-42bc5e35d6eb
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d9d86d07-b2a4-4b49-8021-c8ef13af1404
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Navigation
        sortOrder: 1
handle: services
name: Services
