enableVersioning: true
handle: aboutUs
name: 'About us'
propagationMethod: all
siteSettings:
  a444331c-5954-495c-be67-635a384e66c6:
    enabledByDefault: true
    hasUrls: true
    template: general
    uriFormat: about-us
type: single
