enableVersioning: true
handle: caseStudiesPosts
name: 'Case Studies Posts'
propagationMethod: all
siteSettings:
  a444331c-5954-495c-be67-635a384e66c6:
    enabledByDefault: true
    hasUrls: true
    template: casestudies/_entry
    uriFormat: 'case-studies/{slug}'
type: channel
