enableVersioning: true
handle: caseStudies
name: 'Case Studies'
propagationMethod: all
siteSettings:
  a444331c-5954-495c-be67-635a384e66c6:
    enabledByDefault: true
    hasUrls: true
    template: casestudies/index
    uriFormat: case-studies
type: single
