enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  a444331c-5954-495c-be67-635a384e66c6:
    enabledByDefault: true
    hasUrls: true
    template: home
    uriFormat: __home__
type: single
